version: '3.4'

services:

  db:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433"

  identityserver:
    build: ./src/Identity
    ports:
      - '5001:5001'
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection="Server=localhost;Database=DotnetflixDB;User Id=sa;Password=${DB_PASSWORD};"
      - Fido2Configuration__serverDomain=localhost
      - Fido2Configuration__origins=https://localhost:5001
